const blogs = [
  {
    title: "How to Escape world with a good Trip?",
    author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 1,
  },
  {
    title: "How to Escape world with a good Trip?",
    Author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 2,
  },
  {
    title: "How to Escape world with a good Trip?",
    Author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 3,
  },
  {
    title: "How to Escape world with a good Trip?",
    Author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 4,
  },
  {
    title: "How to Escape world with a good Trip?",
    author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 5,
  },
  {
    title: "How not to Escape world with a good Trip?",
    Author: "Anand Raghuvanshi",
    like: 1122,
    comments: {
      commentCount: 5,
      comment: [
        { user: "anand", body: "nice blog" },
        { user: "ashish", body: "beautiful thought" },
        { user: "ankit", body: "incrediable" },
        { user: "ayush", body: "really, I didn't even know" },
        { user: "sumit", body: "nice thought" },
      ],
    },
    time: "29 May, 2022",
    body: "So, as we all are born in this, adventure circle of 7 Hell, i.e is our life. Travelling can be proved as experincing havean.",
    img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/thumb-image_647_060515020243.jpg?size=770:433",
    blogId: 6,
  },
];
export default blogs;
